### ISSUE TITLE
Map Editor

### ISSUE THREAD

**Issue by mrommel** [mrommel/Colony#55]
### Todo

- [x] macos app with map viewer
with terrain, feature, resource, hill, river
- [x] share resources with iOS app
- [x] change terrain / feature / resource / hill / river for each tile
- [x] load and save maps
- [x] import civ5 maps
- [x] generate random map based on options
- [x] show and change flags for start locations
